#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: git-diff ed7b2772f6072a142f138231b71d8633bf56f738"
	echo "Usage: git-diff ed7b2772f6072a142f138231b71d8633bf56f738~2"
	exit
fi

if [[ "$1" =~ \~[0-9]*$ ]]; then 
  cmt=$(echo "$1" | sed 's/\([^\~]*\)\~\([0-9]*\)$/\1/g')
  idx=$(echo "$1" | sed 's/\([^\~]*\)\~\([0-9]*\)$/\2/g')
  echo ">>> Comparing ${cmt}~$(($idx+1)) > ${cmt}~$(($idx))"
  git diff "${cmt}~$(($idx+1))" "${cmt}~$(($idx))"
else
  echo ">>> Comparing ${1}~1 $1"
  git diff "${1}~1" "$1"
fi
