#!/bin/bash

open_oxygen () { 
  /Applications/Oxygen\ XML\ Developer/oxygenDeveloper.sh "$1" >/dev/null 2>&1 &
}

if [ "$1" == "" ]; then
  echo "Usage: ~/scripts/oxygen http://admin:admin@localhost:10989/preview/family-history/content/english/page-10156323304399411548-eng.xml"
  echo "Usage: ~/scripts/oxygen 10989 /preview/family-history/content/english/page-10156323304399411548-eng.xml"
fi

port=10989
host=localhost
credentials="admin:admin"
uri="$1"
if [ ! "$2" == "" ]; then
  port="$1"
  uri="$2"
fi

case $port in
chaw)
  port=10481
  ;;
cha)
  port=20184
  ;;
fh)
  port=10989
  ;;
tfh)
  port=9989
  host=l12869
  credentials="deployment:deployment"
  ;;
arp)
  port=10132
  ;;
tarp)
  port=8901
  host=l16276
  credentials="deployment:deployment"
  ;;
temples)
  port=20104
  ;;
ldse)
  port=9308
  ;;
si)
  port=10944
  ;;
tsi)
  port=9944
  host=l12869
  credentials="deployment:deployment"
  ;;
charities)
  port=9861
  ;;
di)
  port=20134
  ;;
mr)
  port=10179
  ;;
mp)
  port=10214
  ;;
rec)
  port=10219
  ;;
rk)
  port=20174
  ;;
pl)
  port=10242
  ;;
nrc)
  port=8900
  host=l16266
  credentials="deployment:deployment"  
  ;;
nrd)
  port=8901
  host=l16266
  credentials="deployment:deployment"  
  ;;
esac



uri=$(echo "$uri" | sed 's/​//g')

fullUrl=$(chk=$(echo "$uri" | grep "http://") && echo "$?")
fh=$(chk=$(echo "$uri" | grep "family-history") && echo "$?")

if [ "$fullUrl" == "0" ]; then
  open_oxygen "$uri"
else
  # if [ "$fh" == "0" ]; then
  # fi
  echo "http://${credentials}@${host}:${port}${uri}"
  open_oxygen "http://${credentials}@${host}:${port}${uri}"
fi


